
title: Red Belts
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redbelts.github.io/website/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Site Config
site_logo: "/assets/img/logo/logo.png"
copyright_text: "<p>&copy; Copyright 2020 Vinex | All right reserved.</p>"

facebook_url: "https://facebook.com/rubelhossain.31105"
twitter_url: "https://twitter.com/rubel8525"
pinterest_url: "https://pinterest.com/rubel8525"
instagram_url: "https://instagram.com/rubel8525"
