- name: Third-Party Risk Assessment
  icon: /assets/images/icon/pie-chart.png
  description: Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc

- name: Penetration Testing
  icon: /assets/images/icon/rocket.png
  description: Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis

- name: Virtual CISO
  icon: /assets/images/icon/clock.png
  description: Titor lacus luctus accumsan tortor posuere ac ut consequat semper viverra nam libero justo laoreet.
