- name: Third-Party Risk Assessment
  icon: /assets/images/icon/pie-chart.png
  description: A proprietary assessment assisting to gain an understanding of organisation’s cyber threat and defence levels in greater detail.

- name: Penetration Testing
  icon: /assets/images/icon/rocket.png
  description: Identifying known and unknown vulnerabilities in external and internal environments.

- name: Virtual CISO
  icon: /assets/images/icon/clock.png
  description: A tiered offering designed to provide top-tier security experts and their expertise available to all organisations. 
